system:
    debug: 1
    timezone: 'UTC'
database:
    driver: mysql
    host: localhost
    user: root
    password: ''
    name: db_name
    prefix: wind_
session:
    handler: native
    expire_time: 15
cache:
    enabled: 0
    storage: file
    handler: serialize
    dir: cache
    time: 15
language:
    debug: 0
    locale: en-GB
    default: en-GB
    format: ini
    path: resources/languages
ioc:
    registry:
        application: system.application
        authenticate: system.authenticate
        input: system.input
        environment: system.environment
        dispatcher: system.dispatcher
        config: system.config
        database: system.database
        language: system.language
        log: system.logger
        router: system.router
        session: system.session
        cache: system.cache
        debugger: whoops
