system:
    # Enanle debug mode, will disable cache, and log some errors.
    debug: false

    # The PHP error reporting level, 0 is hide all errors, -1 is the biggest report level.
    error_reporting: 0

    # Default system timezone.
    timezone: 'UTC'

    # Secret code will be a salt to generate hashs when system running,
    # Will be replace when Windwalker installation.
    secret: 'This-token-is-not-safe'

error:
    # The error template & renderer engine
    template: windwalker.error.default
    engine: php
    log: false

session:
    # Session handler, supports `native`, `database`, `apc`, `memcached`
    handler: native
    # By minutes
    expire_time: 15

routing:
    # Enable routing debug, if route key not found when you generate routs,
    # will raise error and stop application.
    # @deprecated
    debug: true

    # Simple routing help us auto find controller by URL: `{package}/{controller}` without routing config,
    # Disable this function will enhance performance.
    simple_route: true

cache:
    # Disabled cache will make all cache as null storage and not stored to storage.
    # But you can use CacheFactory::createCache('mycache') to ignore this settings.
    enabled: false

    # The default sotrage, you can use other storages by use `CacheManager::getCache('name', 'storage')`
    # Support storages: file / raw_file / memcached / null / redis / array / runtime_array
    storage: file

    # Cache serializer decided how to serialize and store data into storage.
    # Support serializers: php / json / string / raw
    serializer: php

    # Cache time (minutes)
    time: 15

crypt:
    # The Crypt cipher method.
    # Support ciphers: blowfish (bf) / aes-256 (aes) / 3des / php_aes
    cipher: blowfish

asset:
    # The asset folder in public root, default is `asset`
    folder: asset

    # The full asset uri, default is NULL. If you set this uri, it will override `asset.folder`.
    # This is useful if you want to put all asset files on cloud storage.
    uri: ~

language:
    # Language debug will mark untranslated string by `??` and stored orphan in Languages object.
    debug: false

    # The current locale
    locale: en-GB

    # The default locale, if translated string in current locale not found, will fallback to default locale.
    default: en-GB

    # Dfault languaghe file format, you can use other foramt in runtime by `Translator::loadFile($file, 'yaml')`
    format: ini

console:
    # Custom scripts, add some commands here to batch execute. Example:
    # scripts:
    #     foo:
    #         - git pull
    #         - composer install
    #         - php windwalker migration migrate
    #
    # Then just run `$ php windwalker run foo`
    scripts: ~
